### ISSUE TITLE
Missing libsleef.so.3 when installing sleef 3.6.1 with conda

### ISSUE THREAD

**Issue by michaelvay** [conda-forge/sleef-feedstock#7]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Hi,
When conda installing pytorch in my env which requires sleef I am getting sleef==3.6.1 and its missing libsleef.so.3 that leads to:

`E   ImportError: libsleef.so.3: cannot open shared object file: No such file or directory`

+ sleef                             3.6.1  h3400bea_0                   conda-forge
+ pytorch                           2.3.1  cpu_generic_py312h2f1fc2b_0  conda-forge

Python 3.12.3
Ubuntu18.04.4

**Comment by michaelvay** [comment]
sleef 3.6.1 h3400bea_1 build solves the issue closing.

**Comment by michaelvay** [comment]
sleef 3.6.1 h3400bea_1 build solves the issue closing.

**Comment by bluescarni** [comment]
@michaelvay yes indeed, it seems like in the new version of sleef static libraries are the default and shared libraries are opt in.
